server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"

    sources:
      youtube: false

plugins:
  dependencies:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.2"

youtube:
  enabled: true
  allowSearch: true
  allowDirectVideoIds: true
  allowDirectPlaylistIds: true
  clients:
    - MUSIC
    - WEB

logging:
  level:
    root: INFO
